run:
  build-tags:
    - analyze

linters:
  enable:
    - gofmts

linters-settings:
  custom:
    gofmts:
      path: golangci-lint/plugin.so
      description: gofmts
      original-url: github.com/ashanbrown/gofmts

issues:
  exclude-rules:
    - path: cmd/gofmts/gofmt.go
      linters:
        - errcheck
