- id: gofmts
  name: gofmts
  language: golang
  entry: gofmts -l -w
  types: [go]

- id: gofmts-docker
  name: gofmts
  language: docker_image
  entry: ghcr.io/ashanbrown/gofmts:latest -l -w
  types: [go]
