name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        env:
          SKIP: no-commit-to-branch
      - name: Run tests
        run: make test
      - name: Test out exported pre-commit hook
        run: pre-commit try-repo . gofmts --verbose --files pkg/gocmts/*
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
